baseURL = 'https://yourname.github.io'
languageCode = 'en-us'
title = 'Roy Jara'
theme = 'book'

# Book theme params
[params]
  # Disable book-specific features
  BookSearch = false
  BookComments = false
  BookEditPage = false
  BookDateFormat = "2006-01-02"
  
  # Portfolio-specific
  BookToC = true
  BookMenuBundle = true
  BookSection = "*"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6